### ISSUE TITLE
module 'inspect' has no attribute 'getargspec'

### ISSUE THREAD

**Issue by grumpynho** [archivczsk/archivczsk#10]
openATV 7.2 
![openATV 7 2](https://user-images.githubusercontent.com/116819013/204220622-13f905ff-4b75-4c2c-83a2-6a0dee8af4ba.jpg)

**Comment by skyjet18** [comment]
Opravené vo verzii [1.5.9](https://github.com/archivczsk/archivczsk/releases/tag/v1.5.9)
