### ISSUE TITLE
iprima is not able to log in

### ISSUE THREAD

**Issue by YuriSKK** [archivczsk/archivczsk#11]
Hello,
 do you have working iprima with free account login ?
 It's messaging that user authorisation is not possible :(

Martin

**Comment by skyjet18** [comment]
We know about this problem. Addon for iPrima sa based on Kodi's addon from Roman Smolka. This Kodi addon is not maintaned anymore. Prima closed it's previous service called iPrima and migrated everything to iPrima+. This service is completely new and different. To support iPrima+ it's needed to create completely new addon from scratch. But we don't have currently enough man power to do this ... In next release iPrima addon will be removed from repository.
Next time please report addon related problems here: https://github.com/archivczsk/archivczsk-doplnky
Thank you!
