### ISSUE TITLE
Archiv CZ/SK - Doplněk Stream cinema comunity - neukazuje streamovací rychlost při výběru videa

### ISSUE THREAD

**Issue by peeetrch** [archivczsk/archivczsk#14]
Na openATV6.4  plugin Archiv CZ/SK - Stream cinema comunity - neukazuje streamovací rychlost při výběru videa. Doplněk ukazuje jen velikost videí, ale už ne rychlost streamování. Je to chyba nebo změna funkcionality? Lze případně doplnit?

**Comment by skyjet18** [comment]
Toto sa netýka ArchivCZSK ale doplnkov. Každopádne Je to vlastnosť - do jedného riadku je možné vložiť len obmedzené množstvo údajov, tak som info o bitrate vyhodil. Možno v budúcnosti doplním na voľbu ...
